
model:
  model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
  model_max_length: 1024
  torch_dtype_str: "bfloat16"
  trust_remote_code: true
  attn_implementation: "sdpa"
  load_pretrained_weights: true

data:
  train:
    datasets:
      - dataset_name: "text_sft"
        dataset_path: "./train.jsonl"
        split: "train"

peft:
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  lora_target_modules:
    - q_proj
    - v_proj
    - k_proj
    - o_proj

training:
  trainer_type: "TRL_SFT"
  use_peft: true
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2
  learning_rate: 3e-4
  max_steps: 582
  logging_steps: 10
  save_steps: 200
  run_name: "cicd_auto_healer"
  output_dir: "./output"
  save_final_model: true
  warmup_steps: 100
  lr_scheduler_type: "cosine"
  weight_decay: 0.01
